server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${EUREKA:localhost}:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: vehiculo-service
          uri: lb://vehiculo-service
          predicates:
            - Path=/vehiculo/**
        - id: reparacion-service
          uri: lb://reparacion-service
          predicates:
            - Path=/reparacion/**
        - id: repairvehicle-service
          uri: lb://repairvehicle-service
          predicates:
            - Path=/repairvehicle/**
        - id: reportes-service
          uri: lb://reportes-service
          predicates:
            - Path=/reportes/**