server:
  port: 8081
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/CamilaCarabajal/AutofixMicroservicios
          search-paths: config-data